server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zsj1583893320
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  profiles:
    active: dev
  application:
    name: auth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
interceptor:
  auth-ignore-uris: /api/user/register,/api/user/login
knife4j:
  enable: true